### ISSUE TITLE
luabind fails to build with boost 1.57

### ISSUE THREAD

**Issue by tdsmith** [luabind/luabind#27]
luabind fails to build with boost 1.57.

The errors look like:

```
In file included from src/class.cpp:30:
In file included from ./luabind/class.hpp:93:
In file included from ./luabind/back_reference.hpp:27:
In file included from ./luabind/wrapper_base.hpp:31:
In file included from ./luabind/detail/call_member.hpp:34:
./luabind/object.hpp:556:3: error: no matching function for call to 'operator=='
  LUABIND_OPERATOR_ADL_WKND(==)
```

Here are [full build logs](https://gist.github.com/anonymous/5d628da89053b0a55d3c#file-01-bjam-L17-L45).

**Comment by alex85k** [comment]
I have some "fix" but not sure if it is correct:
https://github.com/DennisOSRM/luabind/pull/3

**Comment by tdsmith** [comment]
Homebrew will carry a slightly different patch that applies against 0.9.1: https://github.com/Homebrew/homebrew/pull/33890#issuecomment-67723688

**Comment by risicle** [comment]
Would a 0.9.2 with this fix be too much to ask for?

**Comment by alex85k** [comment]
https://github.com/rpavlik/luabind seem to have a fix applied
